// <auto-generated />
using System;
using AtasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtasApi.Migrations
{
    [DbContext(typeof(AtasDbContext))]
    [Migration("20251126044225_AddSincronizacaoLog")]
    partial class AddSincronizacaoLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtasApi.Models.AtaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtaId")
                        .HasColumnType("integer")
                        .HasColumnName("ata_id");

                    b.Property<string>("ClassificacaoFornecedor")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("classificacao_fornecedor");

                    b.Property<int>("CodigoItem")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_item");

                    b.Property<DateTime?>("DataHoraExclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora_exclusao");

                    b.Property<string>("DescricaoItemOriginal")
                        .HasColumnType("text")
                        .HasColumnName("descricao_item_original");

                    b.Property<bool>("ItemExcluido")
                        .HasColumnType("boolean")
                        .HasColumnName("item_excluido");

                    b.Property<decimal?>("MaximoAdesao")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("maximo_adesao");

                    b.Property<string>("NiFornecedor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ni_fornecedor");

                    b.Property<string>("NomeRazaoSocialFornecedor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_razao_social_fornecedor");

                    b.Property<string>("NumeroItem")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_item");

                    b.Property<decimal?>("PercentualMaiorDesconto")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("percentual_maior_desconto");

                    b.Property<decimal?>("QuantidadeEmpenhada")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantidade_empenhada");

                    b.Property<decimal?>("QuantidadeHomologadaItem")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantidade_homologada_item");

                    b.Property<decimal?>("QuantidadeHomologadaVencedor")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantidade_homologada_vencedor");

                    b.Property<string>("SituacaoSicaf")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("situacao_sicaf");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("valor_total");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("CodigoItem");

                    b.HasIndex("AtaId", "CodigoItem", "NumeroItem")
                        .IsUnique();

                    b.ToTable("ata_item", (string)null);
                });

            modelBuilder.Entity("AtasApi.Models.AtaRegistroPreco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnoCompra")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("ano_compra");

                    b.Property<string>("CodigoModalidadeCompra")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("codigo_modalidade_compra");

                    b.Property<string>("CodigoUnidadeGerenciadora")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_unidade_gerenciadora");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_assinatura");

                    b.Property<DateTime?>("DataHoraAtualizacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora_atualizacao");

                    b.Property<DateTime?>("DataHoraInclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora_inclusao");

                    b.Property<DateTime>("DataVigenciaFinal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vigencia_final");

                    b.Property<DateTime>("DataVigenciaInicial")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vigencia_inicial");

                    b.Property<string>("IdCompra")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_compra");

                    b.Property<string>("NomeModalidadeCompra")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome_modalidade_compra");

                    b.Property<string>("NomeUnidadeGerenciadora")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_unidade_gerenciadora");

                    b.Property<string>("NumeroAta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_ata");

                    b.Property<string>("NumeroCompra")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_compra");

                    b.Property<string>("NumeroControlePncpAta")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_controle_pncp_ata");

                    b.Property<string>("NumeroControlePncpCompra")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_controle_pncp_compra");

                    b.HasKey("Id");

                    b.HasIndex("DataVigenciaFinal");

                    b.HasIndex("NumeroControlePncpAta")
                        .IsUnique();

                    b.HasIndex("NumeroAta", "CodigoUnidadeGerenciadora")
                        .IsUnique();

                    b.ToTable("ata_registro_preco", (string)null);
                });

            modelBuilder.Entity("AtasApi.Models.Item", b =>
                {
                    b.Property<int>("CodigoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("codigo_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodigoItem"));

                    b.Property<int?>("CodigoPdm")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_pdm");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("DescricaoPrincipal")
                        .HasColumnType("text")
                        .HasColumnName("descricao_principal");

                    b.Property<string>("NomePdm")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_pdm");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_item");

                    b.HasKey("CodigoItem");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("AtasApi.Models.ItemDescricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoItem")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_item");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_registro");

                    b.Property<string>("DescricaoItem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_item");

                    b.HasKey("Id");

                    b.HasIndex("CodigoItem", "DescricaoItem")
                        .IsUnique();

                    b.ToTable("item_descricao", (string)null);
                });

            modelBuilder.Entity("AtasApi.Models.SincronizacaoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataUltimaTentativa")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_ultima_tentativa");

                    b.Property<string>("ErroMensagem")
                        .HasColumnType("text")
                        .HasColumnName("erro_mensagem");

                    b.Property<int>("ItensProcessados")
                        .HasColumnType("integer")
                        .HasColumnName("itens_processados");

                    b.Property<int>("Pagina")
                        .HasColumnType("integer")
                        .HasColumnName("pagina");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<int>("TotalPaginas")
                        .HasColumnType("integer")
                        .HasColumnName("total_paginas");

                    b.HasKey("Id");

                    b.HasIndex("Pagina")
                        .IsUnique();

                    b.ToTable("sincronizacao_log", (string)null);
                });

            modelBuilder.Entity("AtasApi.Models.AtaItem", b =>
                {
                    b.HasOne("AtasApi.Models.AtaRegistroPreco", "Ata")
                        .WithMany("Itens")
                        .HasForeignKey("AtaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtasApi.Models.Item", "Item")
                        .WithMany("AtaItens")
                        .HasForeignKey("CodigoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ata");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AtasApi.Models.ItemDescricao", b =>
                {
                    b.HasOne("AtasApi.Models.Item", "Item")
                        .WithMany("Descricoes")
                        .HasForeignKey("CodigoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AtasApi.Models.AtaRegistroPreco", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("AtasApi.Models.Item", b =>
                {
                    b.Navigation("AtaItens");

                    b.Navigation("Descricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
